clone_folder: C:\projects\sqlpp11-connector-postgresql

branches:
  only:
  - master
  - develop

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      generator: "Visual Studio 14 2015 Win64"
      configuration: Debug
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      generator: "Visual Studio 15 2017 Win64"
      configuration: Debug
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      generator: "Visual Studio 14 2015 Win64"
      configuration: Release
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      generator: "Visual Studio 15 2017 Win64"
      configuration: Release

services:
  - postgresql101

init:
  - echo %generator%

build_script:
  - PATH=C:\Program Files\PostgreSQL\10\bin\;%PATH%
  - set PGUSER=postgres
  - set PGPASSWORD=Password12!
  - psql -c "CREATE USER test WITH PASSWORD 'test'"
  - createdb test
  - createdb sqlpp_postgresql
  - cd ..
  - git clone --branch v2.4 --depth 1 https://github.com/HowardHinnant/date.git
  - git clone --branch master --depth 1 https://github.com/rbock/sqlpp11.git
  - cd sqlpp11
  - cmake . -DHinnantDate_ROOT_DIR="C:/projects/date" -G "%generator%"
  - cd ../sqlpp11-connector-postgresql
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_PREFIX_PATH="C:/Program Files;C:/projects/sqlpp11/cmake" -DCMAKE_MODULE_PATH="C:/projects/sqlpp11/cmake/Modules" -DHinnantDate_ROOT_DIR="C:/projects/date" -DSqlpp11_DIR="C:/projects/sqlpp11" -D -DENABLE_TESTS=True -G "%generator%"
  - cmake --build . --config "%configuration%"
  - ctest . --output-on-failure -C "%configuration%"
