language: cpp

sudo: required
dist: trusty

compiler:
  #- clang
  - gcc

notifications:
  email:
    on_success: change
    on_failure: always

services:
  - postgresql

install:
  - sudo apt-get install -y postgresql-server-dev-all
  - pwd
  - g++ --version
  - cmake --version
  - cd ..
  - git clone https://github.com/HowardHinnant/date
  - cd date
  - git checkout tags/v2.4
  - cmake -DCMAKE_BUILD_TYPE=Release .
  - make && sudo make install
  - cd ..
  - git clone https://github.com/rbock/sqlpp11.git
  - cd sqlpp11
  - cmake -DCMAKE_BUILD_TYPE=Release .
  - make && sudo make install
  - cd ../sqlpp11-connector-postgresql

before_script:
  - mkdir build
  - cd build
  - cmake .. -DSQLPP11_INCLUDE_DIR=/usr/local/include -DDATE_INCLUDE_DIR=/usr/local/include

script:
  - cmake --build .
  - echo -e "sudo -u postgres createuser -l -S -D -R $USER\nsudo -u postgres createdb $USER" > setup_db.sh
  - chmod a+x setup_db.sh
  - sudo ./setup_db.sh
  - ctest --output-on-failure
